apiVersion: v1
kind: Template
metadata:
  name: network-check
parameters:
- name: HTTP_URL
  description: URL to try HTTP GETs against
- name: GETENT_HOST
  description: Hostname to run 'getent host' against
- name: HTTP_TIMEOUT
  description: Timeout in seconds of HTTP GET
- name: GETENT_TIMEOUT
  description: Timeout in seconds of getent command
- name: IMAGE
  value: quay.io/cloudservices/network-check
- name: IMAGE_TAG
  value: latest
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: network-check
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        name: network-check
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: network-check
      spec:
        containers:
        - env:
          - name: HTTP_URL
            value: ${HTTP_URL}
          - name: GETENT_HOST
            value: ${GETENT_HOST}
          - name: HTTP_TIMEOUT
            value: ${HTTP_TIMEOUT}
          - name: GETENT_TIMEOUT
            value: ${GETENT_TIMEOUT}
          image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          name: strimzi-cluster-operator
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 300m
              memory: 500Mi
            requests:
              cpu: 50m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
